name: productivity

on:
  schedule:
    - cron: '*/30 * * * *'  # Chạy mỗi 30 phút
  workflow_dispatch:  # Cho phép chạy thủ công

jobs:
  aggregate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo content
      uses: actions/checkout@v4 # checkout the repository content to GitHub runner

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9' # install the python version needed

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install gspread oauth2client pandas google-auth

    - name: Write Google credentials to file
      env:
        GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
      run: |
        echo "$GOOGLE_APPLICATION_CREDENTIALS" > credentials.json
        
    - name: Set environment variables
      run: |
        echo "LINK=${{ secrets.LINK }}" >> $GITHUB_ENV
        echo "MASTER=${{ secrets.MASTER }}" >> $GITHUB_ENV

    - name: Run productivity script
      env:
        GOOGLE_APPLICATION_CREDENTIALS: credentials.json
        LINK: ${{ secrets.LINK }}
        MASTER: ${{ secrets.MASTER }}
      run: |
        python productivity.py

    - name: Run Performance Management-Nationwide script
      env:
        GOOGLE_APPLICATION_CREDENTIALS: credentials.json
        LINK: ${{ secrets.LINK }}
        MASTER: ${{ secrets.MASTER }}
      run: |
        python "Performance Management-Nationwide.py"
